name: Snyk

on:
  pull_request:
    paths:
      - "extensions/**"
    branches: [main, master]
  workflow_dispatch:
    inputs:
      paths:
        description: 'Extensions to test (space-separated relative paths for extensions) or ("extensions/**"" to execute on all possible subdirectories)'
        required: true

jobs:
  snyk_test:
    if: github.repository == 'raycastbot/snyk'
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed extensions
        id: get_changed_extensions
        uses: raycast/github-actions/get-changed-extensions@v1.11.0
        with:
          custom_paths: ${{ inputs.paths }}
          github_event_name: ${{ github.event_name }}
      - name: Setup Snyk
        uses: snyk/actions/setup@master
      - name: Snyk Test
        working-directory: .github/workflows/
        run: |
          ./snyk_test.sh "${{ inputs.paths }}"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          PATHS: ${{ steps.get_changed_extensions.outputs.paths }}
